### PR TITLE
fix(card): fix card blinking

### LINKED ISSUE #42: [iOS] Map card is blinking when dismissed

### PR DESCRIPTION
**Pull request by leushkin**
closes #42 

Jul-21-2019 16-26-25 2

### CODE REVIEW

File: client/src/components/Modal/atoms.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import styled from 'styled-components/native';
 
-export const Backdrop = styled.TouchableOpacity.attrs({
+export const Backdrop = styled.View.attrs({
```
Comment (lxndr) [inline client/src/components/Modal/atoms.ts]: nice! i feel so stupid right now :rofl:
